### ISSUE TITLE
有几个疑问，辛苦解答一下啊

### ISSUE THREAD

**Issue by nianzixin** [theCakeOfCupid/ModuleManager#1]
1、引入方式：implementation和api都支持么？
2、由于历史原因，每个模块有不同的mavenUrl，这种情况怎么处理？

**Comment by theCakeOfCupid** [comment]
1：都支持，支持所有引入方式的替换
2：只能所有module放在一个仓库里面，现在暂时不支持每个module使用不同的仓库，后续我抽点时间把这个功能加上

**Comment by theCakeOfCupid** [comment]
最新版本已支持模块单独配置mavenUrl
