### ISSUE TITLE
包含libs目录下的aar文件的module发布失败

### ISSUE THREAD

**Issue by qflbai** [theCakeOfCupid/ModuleManager#3]
![image](https://user-images.githubusercontent.com/23705172/126585111-5bd7cb33-4e0d-4baa-b384-345343275779.png)

**Comment by theCakeOfCupid** [comment]
可以参考下这篇文章 https://www.cnblogs.com/baiyuas/p/14383723.html

**Comment by qflbai** [comment]
已经解决。

**Comment by qflbai** [comment]
如果发布时，包含文档和源码的aar，这种插件能支持吗？

**Comment by theCakeOfCupid** [comment]
可以支持

**Comment by theCakeOfCupid** [comment]
可以支持，现在没做这个，后续有时间可以加上这个功能

**Comment by qflbai** [comment]
好的，谢谢。

**Comment by dempsey** [comment]
> 可以参考下这篇文章 https://www.cnblogs.com/baiyuas/p/14383723.html

这篇文章能解决打包，但是打包后无法引用lib里的aar
